---
name: Charles-Étienne
surname: Lavoie
position: "Doctorant en psychologie / Président, nQuerio"
qualifications: "PhD (Cand.)"
address: "2281, Pie IX, Montréal (Québec) H1V 2E6"
phone: 438-393-2410
email: "celavoie96@gmail.com"
headcolor: "333333"
urlcolor: blue
linkcolor: blue
output: 
  vitae::awesomecv:
    page_total: true
header-includes:
  - \usepackage[gen]{eurosym}
  - \usepackage[main=french]{babel}
   # We'll use totpages (not lastpage) to get total pages, avoids duplicate-label warnings
  - \usepackage{totpages}
  # Hook AwesomeCV's footer and rewrite its 3rd argument (page text)
  - \makeatletter
  - \let\origmakecvfooter\makecvfooter
  - \renewcommand{\makecvfooter}[3]{\origmakecvfooter{#1}{#2}{\thepage/\ref{TotPages}}}
  - \makeatother
lang: french
date: "\\today"
papersize: letterpaper
---

```{r setup, include = FALSE}
# Make sure to install babel TeX package
# tinytex::tlmgr_install("babel-french")

# Windows French locale for date
try(Sys.setlocale("LC_TIME", "French_France.1252"), silent = TRUE)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#######################
#### SHORT VERSION ####
#######################

# Whether to print a shortened version of the CV
short <- FALSE

########################
#### PACKAGE SETUP #####
########################

# Required packages
library(vitae)
library(dplyr)

# For Google scholar data/visualization
library(scholar)
library(patchwork)
library(see)
library(rsvg)
library(kableExtra)
library(tidyverse)

language <- "FR" # If not EN, will choose the alternative names in the data
# So far only for nice_awards() and nice_grants()

# To format links throughout the CV
source("files/functions.R")

# Automatically bold your name in the publication section
author_bold <- "Lavoie, C. É."

########################
#### GOOGLE SCHOLAR ####
########################

# Specify your Google scholar profile
scholar.profile <- "6APjQ4AAAAAJ"

# Specify your Google scholar short author name
author.name <- "Charles-Étienne Lavoie"

headcolor <- "0a0a0a"

########################
##### INSTRUCTIONS #####
########################

# Change the order of sections below as desired.
# Edit the individual files ("childs") to edit the content as desired.
# Add `eval = !short` to code chunks to make them optional for the short version

# See all instructions and tips here: https://github.com/rempsyc/cv
```

```{r Education parent, child=c('sections/education.Rmd')}
```

```{r Publications parent, child=c('fr/sections/publications.Rmd')}
```

```{r Preprints parent, child=c('sections/preprints.Rmd'), eval = F}
```

```{r Grants parent, child=c('sections/grant.Rmd'), eval=F}
```



```{r Awards parent, child=c('fr/sections/awards.Rmd')}
```

```{r Teaching parent, child=c('fr/sections/teaching_cel.Rmd')}
```

```{r Invited talks parent, child=c('fr/sections/invited_talks_cel.Rmd'), eval = !short}
```

```{r Conference talks parent, child=c('fr/sections/conference_talks_cel.Rmd'), eval = !short}
```

```{r Conference posters parent, child=c('fr/sections/conference_posters_cel.Rmd'), eval = FALSE}
```

```{r Software parent, child=c('fr/sections/software.Rmd'), eval=F}
```

```{r Academic service parent, child=c('fr/sections/service_cel.Rmd'), eval = !short}
```

```{r Media coverage parent, child=c('fr/sections/media_coverage_cel.Rmd'), eval = !short}
```

```{r References parent, child=c('sections/references.Rmd'), eval = F}
```

<!-- We skip the sections below for now. They are on the website and it was recommended to avoid them for the CV for applying to prof positions -->

```{r Blogs parent, child=c('fr/sections/blogs.Rmd'), eval = F}
```

```{r Other experience parent, child=c('fr/sections/other_experience_cel.Rmd'), eval = TRUE}
```

```{r credit parent, child=c('sections/credit.Rmd'), eval = F}
```

