```{r Conference Poster Presentations, results = "asis"}
nice_header(
  header = "Conference Poster Presentations",
  header_alt = "Communications affichées",
  language = language
)
```

```{r posters_data, results = "asis"}
data <- c(
  "Malchelosse, K., Lavoie, C. É., Masson, R., & Houlfort, N. (2022). *Psychological Needs Satisfaction as a Mediator in the Relationship Between Passion for Work and Work-Life Enrichment*. Poster presentation at the Tenth SELF International Conference.",
  "Malchelosse, K., Lavoie, C. É., Masson, R., & Houlfort, N. (2022). *The relationship between passion for work and the subdimensions of work-life enrichment*. Poster presentation at the 2022 conference of the Société Québécoise pour la Recherche en Psychologie (SQRP).",
  "Lavoie, C. É., Masson, R., Malchelosse, K., & Houlfort, N. (2021). *Effects of supervisor autonomy support on work-family balance: The mediating role of cognitive appraisals*. Poster presentation at the 2021 conference of the Société Québécoise pour la Recherche en Psychologie (SQRP), virtual conference.",
  "Malchelosse, K., Lavoie, C. É., Masson, R., & Houlfort, N. (2021). *Passion and inter-role enrichment: A look at workers with two occupational roles*. Poster presentation at the 2021 conference of the Société Québécoise pour la Recherche en Psychologie (SQRP), virtual conference.",
  "Masson, R., Lavoie, C. É., Malchelosse, K., & Houlfort, N. (2021). *Passion and role performance: A look at the mediating role of psychological needs*. Poster presentation at the 2021 conference of the Société Québécoise pour la Recherche en Psychologie (SQRP), virtual conference.",
  "**Lavoie, C-E.**, Vallerand, R.J., & Verner-Filion, J. (2019). *Passion and emotions: The mediating role of cognitive appraisals*. Poster presentation at the 6th International Positive Psychology Association (IPPA) Conference, Melbourne, Australia.",
  "**Lavoie, C-E.**, Vallerand, R.J., & Verner-Filion, J. (2019). *Passion and emotions: The mediating role of cognitive appraisals*. Poster presentation at the 7th International Conference on Self-Determination Theory, Egmond aan Zee, Netherlands.",
  "**Lavoie, C-E.**, Vallerand, R.J., & Verner-Filion, J. (2018). *The role of cognitive appraisals as mediators of the passion-emotion relationships*. Poster presentation at the 35th Anniversary of the Social Behavior Research Laboratory, Montreal, Canada.",
  "**Lavoie, C-E.**, & Vallerand, R.J. (2018). *The role of cognitive appraisals as mediators of the passion-emotion relationships*. Poster presentation at the 4th Canadian Conference on Positive Psychology, Toronto, Canada.",
  "**Lavoie, C-E.**, & Vallerand, R.J. (2018). *The role of cognitive appraisals as mediators of the passion-emotion relationships*. Poster presentation at the 29th International Congress of Applied Psychology, Montreal, Canada.",
  "Schlobach, M., Ostiguy, D., **Lavoie, C-E.**, and Figueroa Mendez, A. (2016). *Students as producers of intervention instruments: Social innovation at Collège de Maisonneuve*. Poster presentation at the ARC colloquium as part of the 84th Acfas Congress, Montreal, Canada."
)

number_pubs(
  data,
  author_bold = author_bold,
  language = language
)
```
