```{r Conference Poster Presentations, results = "asis"}
nice_header(
    header = "Conference Poster Presentations",
    header_alt = "Communications affichées",
    language = language
)
```

```{r posters_data, results = "asis"}
data <- c(
    "Malchelosse, K., Lavoie, C. É., Masson, R., & Houlfort, N. (2022). *La satisfaction des besoins psychologiques comme médiateur dans la relation entre la passion pour le travail et l'enrichissement travail-vie*. Présentation par affiche à la 10e Conférence internationale SELF.",
    "Malchelosse, K., Lavoie, C. É., Masson, R., & Houlfort, N. (2022). *La relation entre la passion pour le travail et les sous-dimensions de l'enrichissement travail-vie*. Présentation par affiche au congrès 2022 de la Société Québécoise pour la Recherche en Psychologie (SQRP).",
    "Lavoie, C. É., Masson, R., Malchelosse, K., & Houlfort, N. (2021). *Effets du soutien à l'autonomie du superviseur sur l'équilibre travail-famille : Le rôle médiateur des évaluations cognitives*. Présentation par affiche au congrès 2021 de la Société Québécoise pour la Recherche en Psychologie (SQRP), conférence virtuelle.",
    "Malchelosse, K., Lavoie, C. É., Masson, R., & Houlfort, N. (2021). *Passion et enrichissement inter-rôles : Un regard sur les travailleurs ayant deux rôles professionnels*. Présentation par affiche au congrès 2021 de la Société Québécoise pour la Recherche en Psychologie (SQRP), conférence virtuelle.",
    "Masson, R., Lavoie, C. É., Malchelosse, K., & Houlfort, N. (2021). *Passion et performance de rôle : Un regard sur le rôle médiateur des besoins psychologiques*. Présentation par affiche au congrès 2021 de la Société Québécoise pour la Recherche en Psychologie (SQRP), conférence virtuelle.",
    "Lavoie, C-E., Vallerand, R.J., & Verner-Filion, J. (2019). *Passion et émotions : Le rôle médiateur des évaluations cognitives*. Présentation par affiche à la 6e Conférence de l'Association internationale de psychologie positive (IPPA), Melbourne, Australie.",
    "Lavoie, C-E., Vallerand, R.J., & Verner-Filion, J. (2019). *Passion et émotions : Le rôle médiateur des évaluations cognitives*. Présentation par affiche à la 7e Conférence internationale sur la théorie de l'autodétermination, Egmond aan Zee, Pays-Bas.",
    "Lavoie, C-E., Vallerand, R.J., & Verner-Filion, J. (2018). *Le rôle des évaluations cognitives comme médiateurs des relations passion-émotion*. Présentation par affiche au 35e anniversaire du Laboratoire de recherche sur le comportement social, Montréal, Canada.",
    "Lavoie, C-E., & Vallerand, R.J. (2018). *Le rôle des évaluations cognitives comme médiateurs des relations passion-émotion*. Présentation par affiche à la 4e Conférence canadienne de psychologie positive, Toronto, Canada.",
    "Lavoie, C-E., & Vallerand, R.J. (2018). *Le rôle des évaluations cognitives comme médiateurs des relations passion-émotion*. Présentation par affiche au 29e Congrès international de psychologie appliquée, Montréal, Canada.",
    "Schlobach, M., Ostiguy, D., Lavoie, C-E., et Figueroa Mendez, A. (2016). *Les étudiants comme producteurs d'instruments d'intervention : Innovation sociale au Collège de Maisonneuve*. Présentation par affiche au colloque de l'ARC dans le cadre du 84e Congrès de l'Acfas, Montréal, Canada."
)

number_pubs(
    data,
    author_bold = author_bold,
    language = language
)
```
